/**
 * places.js — Loads venue photo data from the pre-fetched static file.
 * data/venue-photos.json is generated by: node scripts/fetch-photos.mjs
 *
 * Supports two formats:
 *   - photoRefs (preferred): photo references served via /api/place-photo proxy
 *   - photoUrls (legacy): direct CDN URLs (may expire)
 */

async function initPlaces() {
  try {
    const resp = await dataFetch('venue-photos.json');
    if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
    const entries = await resp.json();

    const byId = {};
    for (const e of entries) byId[e.id] = e;

    VENUES.forEach(v => {
      const e = byId[v.id];
      if (e?.placeId) v.placeId = e.placeId;
      // Prefer photo references (proxy URLs) over legacy CDN URLs
      if (e?.photoRefs?.length) {
        v.photoUrls = e.photoRefs.map(ref => `/api/place-photo?ref=${encodeURIComponent(ref)}`);
      } else if (e?.photoUrls?.length) {
        v.photoUrls = e.photoUrls;
      }
    });

    if (typeof updateDetailPanel === 'function') updateDetailPanel();
  } catch (err) {
    console.warn('Places: venue-photos.json unavailable —', err.message);
  }
}

// Lazy, memoized photo load. venue-photos.json is ~1 MB and is only consumed
// by the detail panel, so it MUST stay off the boot/map-load critical path
// (it was contending for mobile bandwidth and inflating LCP). Callers:
//   - openDetailPanel (app.js) on first venue open
//   - a one-shot idle warm-up after the map goes idle (app.js)
// Both route here; the fetch fires at most once per session.
let _placesPromise = null;
function ensurePlaces() {
  if (!_placesPromise) _placesPromise = initPlaces();
  return _placesPromise;
}
window.ensurePlaces = ensurePlaces;
