/**
 * places.js — Loads venue photo data from the pre-fetched static file.
 * data/venue-photos.json is generated by: node scripts/fetch-photos.mjs
 *
 * Supports two formats:
 *   - photoRefs (preferred): photo references served via /api/place-photo proxy
 *   - photoUrls (legacy): direct CDN URLs (may expire)
 */

async function initPlaces() {
  try {
    const resp = await dataFetch('venue-photos.json');
    if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
    const entries = await resp.json();

    const byId = {};
    for (const e of entries) byId[e.id] = e;

    VENUES.forEach(v => {
      const e = byId[v.id];
      if (e?.placeId) v.placeId = e.placeId;
      // Prefer photo references (proxy URLs) over legacy CDN URLs
      if (e?.photoRefs?.length) {
        v.photoUrls = e.photoRefs.map(ref => window.apiUrl(`/api/place-photo?ref=${encodeURIComponent(ref)}`));
      } else if (e?.photoUrls?.length) {
        v.photoUrls = e.photoUrls;
      }
    });

    const n = VENUES.filter(v => v.photoUrls?.length).length;
    console.log(`Places: loaded photos for ${n}/${VENUES.length} venues`);
    if (typeof updateDetailPanel === 'function') updateDetailPanel();
  } catch (err) {
    console.warn('Places: venue-photos.json unavailable —', err.message);
  }
}
