// supabase/functions/sync-sun-windows/index.ts
//
// Pulls the nightly-baked sun-windows artifact from
// https://findshades.app/data/sun-windows.json (generated by
// scripts/precompute-sun-windows.mjs in the GH Action) and upserts each
// (venue, date) into public.venue_sun_windows. Triggered by pg_cron once
// daily at 04:30 Oslo, ~4 h after the nightly geometry/sun-window bake
// settles.
//
// Also purges stale rows where for_date < today (Oslo) so the table stays
// at ~8 × 542 = 4336 rows.
//
// ── Deploy ──────────────────────────────────────────────────────────────────
//   supabase functions deploy sync-sun-windows --no-verify-jwt
//
// Required secrets: PUSH_TRIGGER_SECRET (same as send-push, sql/037).
// Required env (auto): SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY.

import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const ARTIFACT_URL = "https://findshades.app/data/sun-windows.json";

interface SunWindowsArtifact {
  v: number;
  generated_at: string;
  dates: string[];
  venues: Record<string, Record<string, { windows: { start: number; end: number }[]; open: number; close: number }>>;
}

function constantTimeEq(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

Deno.serve(async (req) => {
  if (req.method !== "POST") return new Response("Method not allowed", { status: 405 });

  const expected = Deno.env.get("PUSH_TRIGGER_SECRET");
  const supplied = req.headers.get("X-Push-Secret") ?? "";
  if (!expected || !constantTimeEq(expected, supplied)) {
    return new Response("Unauthorized", { status: 401 });
  }

  // Fetch the static JSON from Cloudflare Pages.
  let artifact: SunWindowsArtifact;
  try {
    const resp = await fetch(ARTIFACT_URL, { headers: { "User-Agent": "Shades-sync-sun-windows" } });
    if (!resp.ok) return new Response(`artifact HTTP ${resp.status}`, { status: 502 });
    artifact = await resp.json();
  } catch (e) {
    return new Response(`artifact fetch failed: ${e.message}`, { status: 502 });
  }
  if (!artifact?.venues || !artifact?.dates?.length) {
    return new Response("malformed artifact", { status: 502 });
  }

  // Flatten into rows.
  const rows: { venue_id: string; for_date: string; windows: unknown; open_hour: number; close_hour: number; updated_at: string }[] = [];
  const now = new Date().toISOString();
  for (const venueId of Object.keys(artifact.venues)) {
    const perDate = artifact.venues[venueId];
    for (const date of Object.keys(perDate)) {
      const entry = perDate[date];
      if (!entry || !Array.isArray(entry.windows)) continue;
      rows.push({
        venue_id: venueId,
        for_date: date,
        windows: entry.windows,
        open_hour: entry.open,
        close_hour: entry.close,
        updated_at: now,
      });
    }
  }

  const supabase = createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
  );

  // Upsert in chunks of 1000 to keep the request body within PostgREST limits.
  let upserted = 0;
  for (let i = 0; i < rows.length; i += 1000) {
    const chunk = rows.slice(i, i + 1000);
    const { error } = await supabase
      .from("venue_sun_windows")
      .upsert(chunk, { onConflict: "venue_id,for_date" });
    if (error) {
      return new Response(`upsert chunk ${i / 1000} failed: ${error.message}`, { status: 500 });
    }
    upserted += chunk.length;
  }

  // Purge stale rows — anything strictly before today (Oslo) is useless.
  // Compute Oslo's today as date-only, then use it as the cutoff.
  const today = new Intl.DateTimeFormat("en-CA", {
    timeZone: "Europe/Oslo", year: "numeric", month: "2-digit", day: "2-digit",
  }).format(new Date());
  await supabase.from("venue_sun_windows").delete().lt("for_date", today);

  return new Response(JSON.stringify({ upserted, today, generated_at: artifact.generated_at }), {
    status: 200,
    headers: { "Content-Type": "application/json" },
  });
});
