-- 045-sun-alert-tables.sql — server-side support for the §5a sun-alert
-- migration. Two tables, both deny-all RLS (service-role only).
--
-- 1. venue_sun_windows — pre-baked raw geometric sun windows per
--    (venue_id, date). Populated daily by the sync-sun-windows edge
--    function which pulls https://findshades.app/data/sun-windows.json
--    (generated by scripts/precompute-sun-windows.mjs in the nightly
--    GH Action). One row per venue per date for the next ~8 days.
--
-- 2. weather_oslo — hourly forecast snapshot for Oslo. Populated every
--    30 min by the fetch-weather edge function which pulls met.no
--    locationforecast. ~48 rows at any time (the visible forecast
--    horizon); a TTL purge keeps the table bounded.
--
-- The two tables get joined at sun-alert evaluation time (sql/047
-- process_sun_alerts) — per opted-in user, for each pre-baked window
-- about to start within their lead time, look up the weather for the
-- window's start hour; skip rainy/overcast slices; fire bell row + push.
--
-- Idempotent.

-- ╔════════════════════════════════════════════════════════════════════════╗
-- ║ 1. venue_sun_windows                                                   ║
-- ╚════════════════════════════════════════════════════════════════════════╝
CREATE TABLE IF NOT EXISTS public.venue_sun_windows (
  venue_id   text  NOT NULL,
  for_date   date  NOT NULL,
  windows    jsonb NOT NULL,         -- [{"start": 12.25, "end": 21.5}, ...]
  open_hour  real  NOT NULL,         -- venue.openingHours.open  for that date
  close_hour real  NOT NULL,         -- venue.openingHours.close for that date
  updated_at timestamptz DEFAULT now(),
  PRIMARY KEY (venue_id, for_date)
);

CREATE INDEX IF NOT EXISTS venue_sun_windows_for_date_idx
  ON public.venue_sun_windows (for_date);

ALTER TABLE public.venue_sun_windows ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.venue_sun_windows FROM PUBLIC, anon, authenticated;
-- No policies — only service_role can touch this table. Clients don't
-- need sun-window data; computeSunWindows still runs client-side for
-- the visible pin / list / detail rendering.

-- ╔════════════════════════════════════════════════════════════════════════╗
-- ║ 2. weather_oslo                                                        ║
-- ╚════════════════════════════════════════════════════════════════════════╝
CREATE TABLE IF NOT EXISTS public.weather_oslo (
  forecast_for timestamptz PRIMARY KEY,  -- hour-bucket UTC: 2026-06-01 14:00:00+00
  cloud_pct    real,                     -- 0-100 cloud_area_fraction
  precip_mm    real,                     -- precipitation_amount in mm/h
  symbol_code  text,                     -- met.no symbol_code ('rain','partlycloudy_day', …)
  fetched_at   timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS weather_oslo_fetched_at_idx
  ON public.weather_oslo (fetched_at);

ALTER TABLE public.weather_oslo ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.weather_oslo FROM PUBLIC, anon, authenticated;

-- ╔════════════════════════════════════════════════════════════════════════╗
-- ║ 3. Helpers                                                             ║
-- ╚════════════════════════════════════════════════════════════════════════╝

-- Classify a weather row as rainy/overcast using the same thresholds the
-- client wxBucket uses. precip > 0.1 mm/h → rainy; cloud > 80% w/o rain →
-- overcast. Returns 'sun' / 'skyer' / 'regn' (Norwegian, to match the
-- client's bucket vocabulary).
CREATE OR REPLACE FUNCTION public.wx_bucket(p_for timestamptz)
RETURNS text
LANGUAGE sql
STABLE
SET search_path = public, pg_catalog
AS $$
  SELECT CASE
    WHEN w.precip_mm IS NOT NULL AND w.precip_mm > 0.1                 THEN 'regn'
    WHEN w.cloud_pct IS NOT NULL AND w.cloud_pct > 80                  THEN 'skyer'
    ELSE 'sun'
  END
  FROM public.weather_oslo w
  WHERE w.forecast_for = date_trunc('hour', p_for AT TIME ZONE 'UTC') AT TIME ZONE 'UTC'
  LIMIT 1;
$$;

REVOKE EXECUTE ON FUNCTION public.wx_bucket(timestamptz) FROM PUBLIC, anon, authenticated;

-- Convert an hour-float (12.25 = 12:15) on a given Oslo date to a UTC
-- timestamp aligned to the hour bucket. Used by sql/047 to look up
-- weather_oslo by hour.
CREATE OR REPLACE FUNCTION public.oslo_hour_bucket(p_date date, p_hour real)
RETURNS timestamptz
LANGUAGE sql
IMMUTABLE
SET search_path = public, pg_catalog
AS $$
  SELECT date_trunc(
    'hour',
    (p_date::text || ' ' || floor(p_hour)::int::text || ':00:00')::timestamp
      AT TIME ZONE 'Europe/Oslo'
  );
$$;

REVOKE EXECUTE ON FUNCTION public.oslo_hour_bucket(date, real) FROM PUBLIC, anon, authenticated;

NOTIFY pgrst, 'reload schema';
